### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by 191205** [b0o/surfingkeys-conf#13]
- Surfingkeys Version: Last
- Surfingkeys-conf Version (git hash):
- Operating System: Arch
- Browser Version: Firefox

## Details
Trying to install with issuing gulp install
### Output

```
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/admin/.config/surfkey/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/admin/.config/surfkey/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/admin/.config/surfkey/gulpfile.js:70:6)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by b0o** [comment]
I'm unable to reproduce this. Can you provide your node and gulp versions?

**Comment by jeebak** [comment]
I ran into this too after I tried to update `gulp` after running `npm audit`. The quick workaround would be to run:  `./node_modules/.bin/gulp build`
instead of:  `gulp build` so that you'd be using the local `"gulp": "^3.9.1",` specified in `package.json`.
