### ISSUE TITLE
[Bug] Error when running npm install

### ISSUE THREAD

**Issue by hughanth** [b0o/surfingkeys-conf#74]
- Surfingkeys Version: 1.12
- Surfingkeys-conf Version (git hash): 7c7ceaa
- Operating System: Fedora 37
- Browser Version: Firefox 110.0

## Details

I'm new to this stuff so let me know if this isn't the right place for this.
Forgive me for the long error message. 

Here was my initial problem:

```console
❯ npm install
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm ERR! code 1
npm ERR! path /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! make: Entering directory '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build'
npm ERR!   CXX(target) Release/obj.target/platformFolders/src/binding.o
npm ERR! make: Leaving directory '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.11.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/hugh/Apps/surfingkeys-conf/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/hugh/Apps/surfingkeys-conf/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/hugh/.cache/node-gyp/18.11.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/hugh/.cache/node-gyp/18.11.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/hugh/Apps/surfingkeys-conf/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/hugh/.cache/node-gyp/18.11.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: g++: No such file or directory
npm ERR! make: *** [platformFolders.target.mk:108: Release/obj.target/platformFolders/src/binding.o] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/hugh/Apps/surfingkeys-conf/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 6.1.13-200.fc37.x86_64
npm ERR! gyp ERR! command "/home/hugh/.nvm/versions/node/v18.11.0/bin/node" "/home/hugh/Apps/surfingkeys-conf/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders
npm ERR! gyp ERR! node -v v18.11.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hugh/.npm/_logs/2023-02-28T21_27_24_623Z-debug-0.log
```

So then I tried:

```console
❯ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.11.0 | linux | x64
gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/hugh/.nvm/versions/node/v18.11.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hugh/Apps/surfingkeys-conf/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hugh/.nvm/versions/node/v18.11.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hugh/.cache/node-gyp/18.11.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hugh/.cache/node-gyp/18.11.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/hugh/.nvm/versions/node/v18.11.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hugh/.cache/node-gyp/18.11.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hugh/Apps/surfingkeys-conf',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /home/hugh/Apps/surfingkeys-conf) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/hugh/.nvm/versions/node/v18.11.0/lib/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.1.13-200.fc37.x86_64
gyp ERR! command "/home/hugh/.nvm/versions/node/v18.11.0/bin/node" "/home/hugh/.nvm/versions/node/v18.11.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/hugh/Apps/surfingkeys-conf
gyp ERR! node -v v18.11.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
```

And then

```console
❯ npm install --ignore-scripts --save
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies

added 800 packages, and audited 801 packages in 3s

92 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (1 low, 7 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

❯ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating gulp to 3.9.1, which is a SemVer major change.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

added 134 packages, removed 217 packages, changed 22 packages, and audited 718 packages in 3s

92 packages are looking for funding
  run `npm fund` for details

# npm audit report

lodash  <=4.17.20
Severity: critical
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-x5rq-j2xg-h7qm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-4xc9-xhrj-v574
Prototype Pollution in lodash - https://github.com/advisories/GHSA-fvqr-27wr-82fm
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-29mw-wpgm-hmr9
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
Prototype Pollution in lodash - https://github.com/advisories/GHSA-jf85-cpcp-j695
fix available via `npm audit fix`
node_modules/lodash
  globule  <=1.1.0
  Depends on vulnerable versions of glob
  Depends on vulnerable versions of lodash
  Depends on vulnerable versions of minimatch
  node_modules/globule
    gaze  0.4.0 - 1.0.0
    Depends on vulnerable versions of globule
    node_modules/gaze
      glob-watcher  <=2.0.0
      Depends on vulnerable versions of gaze
      node_modules/glob-watcher

lodash.template  <4.5.0
Severity: critical
Prototype Pollution in lodash - https://github.com/advisories/GHSA-jf85-cpcp-j695
fix available via `npm audit fix --force`
Will install gulp@4.0.2, which is a breaking change
node_modules/gulp-util/node_modules/lodash.template
  gulp-util  >=1.1.0
  Depends on vulnerable versions of lodash.template
  node_modules/gulp-util
    gulp  2.6.1 - 3.9.1
    Depends on vulnerable versions of gulp-util
    Depends on vulnerable versions of vinyl-fs
    node_modules/gulp

minimatch  <=3.0.4
Severity: high
Regular Expression Denial of Service in minimatch - https://github.com/advisories/GHSA-hxm2-r34f-qmc5
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix --force`
Will install gulp@4.0.2, which is a breaking change
node_modules/glob-stream/node_modules/minimatch
node_modules/globule/node_modules/minimatch
  glob  3.0.0 - 5.0.14
  Depends on vulnerable versions of minimatch
  node_modules/glob-stream/node_modules/glob
  node_modules/globule/node_modules/glob
    glob-stream  0.2.0 - 5.2.0
    Depends on vulnerable versions of glob
    Depends on vulnerable versions of minimatch
    node_modules/glob-stream
      vinyl-fs  <=1.0.0
      Depends on vulnerable versions of glob-stream
      Depends on vulnerable versions of glob-watcher
      node_modules/vinyl-fs

11 vulnerabilities (7 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```

And then finally:

```console
❯ npm run gulp install

> surfingkeys-conf@1.1.0 gulp
> npm exec gulp -- install

Error: Could not locate the bindings file. Tried:
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/Debug/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/Release/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/out/Debug/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/Debug/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/out/Release/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/Release/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/default/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/compiled/18.11.0/linux/x64/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/addon-build/release/install-root/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/addon-build/debug/install-root/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/addon-build/default/install-root/platformFolders.node
 → /home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/lib/binding/node-v108-linux-x64/platformFolders.node
    at bindings (/home/hugh/Apps/surfingkeys-conf/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/src/index.js:5:34)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24) {
  tries: [
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/Debug/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/Release/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/out/Debug/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/Debug/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/out/Release/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/Release/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/build/default/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/compiled/18.11.0/linux/x64/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/addon-build/release/install-root/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/addon-build/debug/install-root/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/addon-build/default/install-root/platformFolders.node',
    '/home/hugh/Apps/surfingkeys-conf/node_modules/platform-folders/lib/binding/node-v108-linux-x64/platformFolders.node'
  ]
}
```
I tired googling around for fixing my issues with node-gyp and bindings.gyp but I couldn't find anything.
I also tried switching to different versions of node(17, 18, 19), and re installing node-gyp. 
I also tried the steps you mentioned here: https://github.com/b0o/surfingkeys-conf/issues/66#issuecomment-1287907887
As well as deleting the repository and starting with a fresh clone

```console
❯ npm --version
9.5.0
❯ node --version
v19.7.0
❯ node-gyp --version
v9.3.1
❯ which npm node node-gyp
/home/hugh/.nvm/versions/node/v19.7.0/bin/npm
/home/hugh/.nvm/versions/node/v19.7.0/bin/node
/home/hugh/.nvm/versions/node/v19.7.0/bin/node-gyp
```

Thanks for your help, and I'm a big fan of this project!

**Comment by b0o** [comment]
I think this is the cause, from your initial log:

```
npm ERR! make: g++: No such file or directory
```

Do you have `g++` installed?

```
which g++
```

If it's not installed, [here are some instructions](https://stackoverflow.com/questions/12952913/how-do-i-install-g-for-fedora) on installing it on Fedora. After installing, please try again with a fresh clone of `surfingkeys-conf`. (P.s. I don't recommend running `npm install --ignore-scripts --save` or `npm audit`, I don't think those will help)

Side note: I am going to try finding an alternative to our `platform-folders` dependency. The fact that it requires building with `node-gyp` seems to be a big source of issues.

**Comment by hughanth** [comment]
That fixed it! Thanks for the help, I can't believe I missed that, I kept looking in the wrong place.

**Comment by b0o** [comment]
Awesome!
